import type { AxiosError } from 'axios'
import { i18n, label } from '@/i18n'
import type { ApiEnvelope } from '@/api/types'

// The backend answers in English. Every message it can send is matched here
// and shown in the current language; a message that isn't recognised (e.g. a
// raw database error) falls through unchanged, so nothing is ever hidden.
type Rule = { re: RegExp; key: string; params?: (m: RegExpMatchArray) => Record<string, unknown> }

const rules: Rule[] = [
  { re: /^Invalid credentials or session expired\.$/, key: 'apiErrors.unauthorized' },
  { re: /^You do not have permission to perform this action\.$/, key: 'apiErrors.forbidden' },
  { re: /^The requested resource was not found\.$/, key: 'apiErrors.notFound' },
  { re: /^Too many failed attempts\. Try again later\.$/, key: 'apiErrors.accountLocked' },
  { re: /^This account has been disabled\.$/, key: 'apiErrors.accountDisabled' },
  { re: /^Amount received is less than the amount due\.$/, key: 'apiErrors.insufficientCash' },
  { re: /^Something went wrong\. Please try again\.$/, key: 'common.somethingWrong' },
  { re: /^One or more fields are invalid\.$/, key: 'apiErrors.validation' },
  { re: /^This till is not registered\.$/, key: 'apiErrors.tillNotRegistered' },
  { re: /^branch_id must be a number\.$/, key: 'apiErrors.invalidBranch' },
  { re: /^This branch has sales and can't be deleted/, key: 'apiErrors.branchInUse' },
  { re: /^You can't disable your own account\.$/, key: 'apiErrors.cannotDisableSelf' },
  { re: /^You can't delete your own account\.$/, key: 'apiErrors.cannotDeleteSelf' },
  { re: /^This user has sales, shifts or other activity and can't be deleted\. Deactivate the account instead\.$/, key: 'apiErrors.userInUse' },
  { re: /^Choose a CSV file to import\.$/, key: 'apiErrors.importFileRequired' },
  { re: /^A purchase order that has received stock can't be deleted/, key: 'apiErrors.poLockedDelete' },
  { re: /^A received purchase order can't be edited\.$/, key: 'apiErrors.poLockedEdit' },
  { re: /^This purchase order is already (\w+)\.$/, key: 'apiErrors.poNotReceivable', params: (m) => ({ status: label('poStatus', m[1]) }) },
  { re: /^Reassign this role's users before deleting it\.$/, key: 'apiErrors.roleInUse' },
  { re: /^The Owner role is locked and can't be changed\.$/, key: 'apiErrors.roleLockedChange' },
  { re: /^The Owner role is locked and can't be deleted\.$/, key: 'apiErrors.roleLockedDelete' },
  { re: /^Only a paid sale can be voided\.$/, key: 'apiErrors.saleNotVoidable' },
  { re: /^Only a paid sale can be edited\.$/, key: 'apiErrors.saleNotEditable' },
  { re: /^This till already has an open shift\.$/, key: 'apiErrors.shiftAlreadyOpen' },
  // More specific "can't be edited" first — the generic "closed shift" rule
  // below would otherwise match it too (no $ anchor) with the wrong wording.
  { re: /^This sale belongs to a closed shift and can't be edited\.$/, key: 'apiErrors.saleShiftClosedEdit' },
  { re: /^This sale belongs to a closed shift/, key: 'apiErrors.saleShiftClosed' },
  { re: /^This sale now totals more than the cash received/, key: 'apiErrors.saleEditExceedsCash' },
  { re: /^This shift is already closed\.$/, key: 'apiErrors.shiftClosed' },
  { re: /^Open a shift on this till before selling\.$/, key: 'apiErrors.shiftRequired' },
  { re: /^This supplier has purchase orders and can't be deleted\.$/, key: 'apiErrors.supplierInUse' },
  { re: /^This till has shift history and can't be deleted/, key: 'apiErrors.tillInUse' },
  { re: /^That till isn't registered or is inactive\.$/, key: 'apiErrors.unknownDevice' },
  { re: /^Product #(\d+) isn't available for sale\.$/, key: 'apiErrors.productUnavailable', params: (m) => ({ id: m[1] }) },
  { re: /^Not enough stock for (.+) \((-?\d+) left\)\.$/, key: 'apiErrors.insufficientStock', params: (m) => ({ name: m[1], left: m[2] }) },
  { re: /^Your role can discount at most (\d+)% of a sale\.$/, key: 'apiErrors.discountLimit', params: (m) => ({ percent: m[1] }) },
  // field-level messages
  { re: /^Enter an amount in USD or KHR\.$/, key: 'apiErrors.enterAmount' },
  { re: /^That branch code is already in use\.$/, key: 'apiErrors.branchCodeUsed' },
  { re: /^That device key is already registered\.$/, key: 'apiErrors.deviceKeyUsed' },
  { re: /^Use the format YYYY-MM-DD\.$/, key: 'apiErrors.dateFormat' },
  { re: /^Must be zero or more\.$/, key: 'apiErrors.zeroOrMore' },
  { re: /^A role with that name already exists\.$/, key: 'apiErrors.roleNameUsed' },
  { re: /^Password must be at least 8 characters\.$/, key: 'apiErrors.passwordShort' },
  { re: /^A customer with that phone number already exists\.$/, key: 'apiErrors.phoneUsed' },
  { re: /^PIN must be exactly 4 digits\.$/, key: 'apiErrors.pinFormat' },
  { re: /^That username is already taken\.$/, key: 'apiErrors.usernameUsed' },
  { re: /^The request body is not valid JSON/, key: 'apiErrors.badBody' },
  // generated by the validator: "<Field name> is required." etc.
  { re: /^(.+) is required\.$/, key: 'apiErrors.required', params: (m) => ({ field: m[1] }) },
  { re: /^(.+) is out of range\.$/, key: 'apiErrors.outOfRange', params: (m) => ({ field: m[1] }) },
  { re: /^(.+) must be one of the allowed options\.$/, key: 'apiErrors.oneOf', params: (m) => ({ field: m[1] }) },
  { re: /^(.+) is not valid\.$/, key: 'apiErrors.notValid', params: (m) => ({ field: m[1] }) },
]

// "Name en" -> the translated field name when we have one, else as sent.
function fieldName(raw: string): string {
  const slug = raw.trim().toLowerCase().replace(/\s+/g, '_')
  const key = `fields.${slug}`
  return i18n.global.te(key) ? i18n.global.t(key) : raw
}

export function translateServerMessage(message: string): string {
  for (const rule of rules) {
    const m = message.match(rule.re)
    if (!m) continue
    const params = rule.params?.(m) ?? {}
    if (typeof params.field === 'string') params.field = fieldName(params.field)
    return i18n.global.t(rule.key, params)
  }
  return message
}

// The message to show for a failed API call: the first field-level message if
// there is one (more specific), otherwise the general one, translated.
export function apiErrorMessage(err: unknown, fallbackKey = 'common.somethingWrong'): string {
  const axiosErr = err as AxiosError<ApiEnvelope<unknown>>
  if (!axiosErr?.response) return i18n.global.t('common.serverUnreachable')
  const body = axiosErr.response.data?.error
  const fields = body?.fields
  const raw = (fields && Object.values(fields)[0]) ?? body?.message
  return raw ? translateServerMessage(raw) : i18n.global.t(fallbackKey)
}
